name: Docs

on:
  #push:
  #  branches-ignore:
  #    - '**'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: Requirements
        run: brew install python3
          && python3 -m ensurepip --default-pip
          && python3 -m pip install --upgrade pip setuptools wheel
          && brew install doxygen
          && brew install sphinx-doc
          && pip3 install sphinx-rtd-theme
          && python3 -m pip install "breathe==4.31.0"
          && pip3 install sphinx-sitemap
          && python3 -m pip install "exhale" &&
      - name: Checkout repo
        uses: actions/checkout@1.0.0
      - name: Build docs
        run: cd docs-sphinx
          && make html
          && cd _build 
          && rm .nojekyll
          && cd html
          && touch .nojekyll
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs-sphinx/_build/html # The folder the action should deploy.
